/*
 * uart.c
 *
 *  Created on: Oct 29, 2023
 *      Author: HP
 */

#include "bitmap.h"
#include"AvrRegisters.h"
#include"stdtypes.h"
#include "uart.h"

void USART_Init()
{
#if(MODE_OF_OPERATION==ASYNCHRONOUS)
	SET_BIT(UCSRC,URSEL_ID);
	CLEAR_BIT(UCSRC,UMSEL_ID);
#elif (MODE_OF_OPERATION==SYNCHRONOUS)
	SET_BIT(UCSRC,URSEL_ID);
	SET_BIT(UCSRC,UMSEL_ID);
	CLEAR_BIT(UCSRA,U2X_ID);
#endif

#if(SPEED_OPERATION	==DOUBLE_SPEED_MODE)
	SET_BIT(UCSRA,U2X_ID);
#elif(SPEED_OPERATION	==NORMAL_SPEED_MODE)
	CLEAR_BIT(UCSRA,U2X_ID);
#endif

#if(PARITY_MODE	== DISABLED)
	SET_BIT(UCSRC,URSEL_ID);
	CLEAR_BIT(UCSRC,UPM0_ID);
	CLEAR_BIT(UCSRC,UPM1_ID);

#elif(PARITY_MODE == EVEN_PARITY)
	SET_BIT(UCSRC,URSEL_ID);
	CLEAR_BIT(UCSRC,UPM0_ID);
	SET_BIT(UCSRC,UPM1_ID);
#elif (PARITY_MODE == ODD_PARITY)
	SET_BIT(UCSRC,URSEL_ID);
	SET_BIT(UCSRC,UPM0_ID);
	SET_BIT(UCSRC,UPM1_ID);
#endif

#if(STOP_BIT_SELECT	== TWO_BIT)
	SET_BIT(UCSRC,URSEL_ID);
	SET_BIT(UCSRC,USBS_ID);
#elif(STOP_BIT_SELECT==ONE_BIT)
	SET_BIT(UCSRC,URSEL_ID);
	CLEAR_BIT(UCSRC,USBS_ID);
#endif

#if (FRAME_SIZE	== 8)
	SET_BIT(UCSRC,URSEL_ID);
	CLEAR_BIT(UCSRB,UCSZ2_ID);
	SET_BIT(UCSRC,UCSZ1_ID);
	SET_BIT(UCSRC,UCSZ0_ID);
#endif

#if(BAUD_RATE==9600)
#if(F_CPU==16000000)

#if(SPEED_OPERATION	==DOUBLE_SPEED_MODE)
	//UBRRH=0;
	UBRRL = 207;
#elif(SPEED_OPERATION	==NORMAL_SPEED_MODE)
	UBRRL = 103;
#endif
#endif
#if(F_CPU==8000000)

#if(SPEED_OPERATION	==DOUBLE_SPEED_MODE)
	UBRRL = 103;
#elif(SPEED_OPERATION	==NORMAL_SPEED_MODE)
	UBRRL = 51;
#endif
#endif

#endif //baudrate

 //rx and tx enable
	SET_BIT(UCSRB,RXEN_ID);
	SET_BIT(UCSRB,TXEN_ID);

}

void USART_Transmit( u8 data ){
	while(BIT_IS_CLEAR(UCSRA,UDRE_ID));
	UDR = data;
}

u8 USART_Receive(){
	u8 data;
	while(BIT_IS_CLEAR(UCSRA,RXC_ID));
	data = UDR;
	return data;
}
